import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";

// Use only valid weights (300, 400, 700, 900)
const merriweather = Merriweather({
  subsets: ["latin"], // Correct subset
  weight: ['300','400','700'], // Correct weight values
  variable: "--font-merriweather", // Custom variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriweather.variable}>{children}</body>
    </html>
  );
}
