export const projects = [
  {
    title: "Portfolio Next.js Css",
    description: "Created Portfolio with next.js & css",
    techStack: ['Next.js', 'Tailwind CSS', 'D3.js'],
           image: '/projects/1.png',
    link: 'https://portfolio-css-knai.vercel.app/',
  },
  {
    title: "Figma Food Project",
    description: "Created figma project with next.js",
    techStack: ['React', 'Redux', 'Stripe API'],
          image: '/projects/2.png',
    link: 'https://food-knai.vercel.app/',
  },
  {
    title: "Perfume Clone Website",
    description: "Created my first project with next.js",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/3.png',
    link: 'https://perfume-knai.vercel.app/',
  },
  {
    title: "Hackathon Resume-4",
    description: "Created figma project with html & css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/4.png',
    link: 'https://milestone4-knai.vercel.app/',
  },
  {
    title: "Countdown Timer",
    description: "Created Counter project with next.js",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
             image: '/projects/5.png',
    link: 'https://count-down-timer-knai.vercel.app/',
  },
  {
    title: "Counter Project",
    description: "Created Counter project with html & css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
                   image: '/projects/6.png',
    link: 'https://counter-application-knai.vercel.app/',
  },
  {
    title: "Palaindrome Project",
    description: "Created Palaindrome project with html & css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
                   image: '/projects/7.png',
    link: 'https://palindrome-knai.vercel.app/',
  },
  {
    title: "Assignment-12 Project",
    description: "Created project with html & css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/8.png',
    link: 'https://assignment-12-knai.vercel.app/',
  },
  {
    title: "Facebook Login Page",
    description: "Created my first project with next.js",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/9.png',
    link: 'https://github.com/nida1khurram/fb_login_pg',
  },
  {
    title: "Periodic Table Project",
    description: "Created Periodic project with html & css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
                   image: '/projects/10.png',
    link: 'https://assignment6-periodic-table.vercel.app/',
  },
  {
    title: "Currency Converter",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
                   image: '/projects/11.png',
    link: 'https://github.com/nida1khurram/currency_converter',
  },
  {
    title: "Number Guessing Game",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/12.png',
    link: 'https://github.com/nida1khurram/num_guessing_game_color',
  },
  {
    title: "Atm Project",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
          image: '/projects/13.png',
    link: 'https://github.com/nida1khurram/Project_atm',
  },
  {
    title: "Todo List",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
          image: '/projects/14.png',
    link: 'https://github.com/nida1khurram/todo_list',
  },
  {
    title: "Word Counter",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/15.png',
    link: 'https://github.com/nida1khurram/word_counter',
  },
  {
    title: "OOP Assignment",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
          image: '/projects/16.png',
    link: 'https://github.com/nida1khurram/Oop-assignment',
  },
  {
    title: " Simple Calculator",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/17.png',
    link: 'https://github.com/nida1khurram/color_simple_calculator',
  },
  {
    title: "Typescript Assignment",
    description: "Created project TypeScript/Node.js project",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/18.png',
    link: 'https://github.com/nida1khurram/typescript_ass001',
  },
  {
    title: "Milestone-Blog",
    description: "Created next.js,typescript and tailwind-css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
                   image: '/projects/19.jpg',
    link: 'https://knai-blog-milestone.vercel.app/',
  },
  {
    title: "Ecomemerce Practice",
    description: "Created next.js,typescript and tailwind-css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
          image: '/projects/20.png',
    link: 'https://ecommerce-hakathon-demo.vercel.app/',
  },
  {
    title: "Milestone 3",
    description: "Created next.js,typescript and tailwind-css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/21.png',
    link: 'https://milestone3-watch-ecommerce.vercel.app/',
  },
  {
    title: "Milestone 2",
    description: "Created next.js,typescript and tailwind-css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/22.webp',
    link: 'https://milestone2knai.vercel.app/',
  },
  {
    title: "Hackathon Website",
    description: "Created next.js,typescript and tailwind-css",
    techStack: ['Next.js', 'OpenAI API', 'Cloudinary'],
           image: '/projects/23.png',
    link: 'https://foodtuck-hac3.vercel.app/',
  },
];
